# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "virtio_scsi" "sr_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  boot.zfs.devNodes = "/dev/disk/by-uuid";

  fileSystems."/" = {
      device = "none";
      fsType = "tmpfs";
  };

  fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/4879-77EA";
      fsType = "vfat";
  };

  fileSystems."/nix" = {
      device = "rpool/local/nix";
      fsType = "zfs";
      options = [ "zfsutil" ];
  };

  fileSystems."/persist" = {
      device = "rpool/safe/persist";
      fsType = "zfs";
      options = [ "zfsutil" ];
      neededForBoot = true;
  };

  fileSystems."/persist/data" = {
      device = "rpool/safe/persist/data";
      fsType = "zfs";
      options = [ "zfsutil" ];
      neededForBoot = true;
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}

